name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          git config --global user.email "your-email@example.com"
          git config --global user.name "Your Name"
          git checkout --orphan gh-pages
          git --work-tree dist add --all
          git --work-tree dist commit -m "Deploy"
          git --work-tree dist push origin HEAD:gh-pages --force

